import { Pokemon } from '@/types/pokemon';

export const mockPokemon: Pokemon = {
  id: 1,
  name: 'Bulbasaur',
  type: 'grass',
  types: ['grass', 'poison'],
  height: 0.7,
  weight: 6.9,
  abilities: ['Overgrow', 'Chlorophyll'],
  stats: {
    hp: 45,
    attack: 49,
    defense: 49,
    spAtk: 65,
    spDef: 65,
    speed: 45,
  },
  imageUrl: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/1.png',
  siblings: {
    prev: { id: 151, name: 'Mew' },
    current: { id: 1, name: 'Bulbasaur' },
    next: { id: 2, name: 'Ivysaur' },
  },
};

export const mockPokemonList: Pokemon[] = [
  mockPokemon,
  {
    id: 2,
    name: 'Ivysaur',
    type: 'grass',
    types: ['grass', 'poison'],
    height: 1.0,
    weight: 13.0,
    abilities: ['Overgrow', 'Chlorophyll'],
    stats: {
      hp: 60,
      attack: 62,
      defense: 63,
      spAtk: 80,
      spDef: 80,
      speed: 60,
    },
    imageUrl: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/2.png',
    siblings: {
      prev: { id: 1, name: 'Bulbasaur' },
      current: { id: 2, name: 'Ivysaur' },
      next: { id: 3, name: 'Venusaur' },
    },
  },
  {
    id: 3,
    name: 'Venusaur',
    type: 'grass',
    types: ['grass', 'poison'],
    height: 2.0,
    weight: 100.0,
    abilities: ['Overgrow', 'Chlorophyll'],
    stats: {
      hp: 80,
      attack: 82,
      defense: 83,
      spAtk: 100,
      spDef: 100,
      speed: 80,
    },
    imageUrl: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/3.png',
    siblings: {
      prev: { id: 2, name: 'Ivysaur' },
      current: { id: 3, name: 'Venusaur' },
      next: { id: 4, name: 'Charmander' },
    },
  },
  {
    id: 4,
    name: 'Charmander',
    type: 'fire',
    types: ['fire'],
    height: 0.6,
    weight: 8.5,
    abilities: ['Blaze', 'Solar Power'],
    stats: {
      hp: 39,
      attack: 52,
      defense: 43,
      spAtk: 60,
      spDef: 50,
      speed: 65,
    },
    imageUrl: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/4.png',
    siblings: {
      prev: { id: 3, name: 'Venusaur' },
      current: { id: 4, name: 'Charmander' },
      next: { id: 5, name: 'Charmeleon' },
    },
  },
  {
    id: 7,
    name: 'Squirtle',
    type: 'water',
    types: ['water'],
    height: 0.5,
    weight: 9.0,
    abilities: ['Torrent', 'Rain Dish'],
    stats: {
      hp: 44,
      attack: 48,
      defense: 65,
      spAtk: 50,
      spDef: 64,
      speed: 43,
    },
    imageUrl: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/7.png',
    siblings: {
      prev: { id: 6, name: 'Charizard' },
      current: { id: 7, name: 'Squirtle' },
      next: { id: 8, name: 'Wartortle' },
    },
  },
  {
    id: 25,
    name: 'Pikachu',
    type: 'electric',
    types: ['electric'],
    height: 0.4,
    weight: 6.0,
    abilities: ['Static', 'Lightning Rod'],
    stats: {
      hp: 35,
      attack: 55,
      defense: 40,
      spAtk: 50,
      spDef: 50,
      speed: 90,
    },
    imageUrl: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/25.png',
    siblings: {
      prev: { id: 24, name: 'Arbok' },
      current: { id: 25, name: 'Pikachu' },
      next: { id: 26, name: 'Raichu' },
    },
  },
];
